---
title: "Testing and timing flowcut"
author: Sangwon Hyun
date: "June 4th, 2026"
output:
  html_document:
    number_sections: true
---

This code tests and times `flowcut()`.

Setting up

```{r, eval = FASLE}
## Installing the package
install.packages("~/repos/flowmix-fork/flowmix", type = 'source', repos = NULL)

## Possibly remove all .o and .so files in src/. before doing this.
devtools::document("~/repos/flowmix-fork/flowmix")
devtools::build("~/repos/flowmix-fork/flowmix", vignettes = FALSE)
devtools::install("~/repos/flowmix-fork/flowmix", vignettes = FALSE)
```

Generate some data. and measure flowcut run times.


```{r}
library(flowmix)
## library(parallel)
##library(parallelly)
library(tidyverse)
devtools::load_all("~/repos/flowmix-fork/flowmix")
  
## General setup
TT = 100
nt = 1000
prob1 = 3/4
fac = .2
dimdatt = 2
numclust = 2
##censoring_limit = 3.5
censoring_limit = 2
maxdev = .5
## maxdev = .225
  
## Amount of censoring
cens_vec_1 = c(-Inf,-Inf,rep(-Inf, dimdatt-2))
cens_vec_2 = c(Inf,censoring_limit, rep(Inf, dimdatt-2))
  
  
## Generate data
set.seed(100)
datobj <-   gendat_flowcut(TT = TT, fac = .2 , nt = nt,
                           cens_lim_l_vec = cens_vec_1,
                           cens_lim_u_vec = cens_vec_2)
datobj %>% list2env(envir = .GlobalEnv) %>% invisible()

## Roughly plotting the data
y1 = ylist %>% sapply(function(a) a[,1])  %>% do.call(rbind, .)
y2 = ylist %>% sapply(function(a) a[,2])  %>% do.call(rbind, .)
y2 %>% matplot(type='p', pch = 16, col = rgb(0,0,0,0.1), main = "Dimension 2")
abline(h=censoring_limit, col = 'red')
  
## Fit model and measure the time
devtools::load_all("~/repos/flowmix-fork/flowmix")
flowcut_profvis = profvis::profvis({
  set.seed(99)
  oneres_flowcut <- flowcut_once(
      ylist = ylist,
      countslist = NULL,
      X = X,
      prob_lambda = 0.001,
      mean_lambda = 0.001,
      cens_indicator_list_left  = censor_indicator_left,
      cens_indicator_list_right = censor_indicator_right,
      cens_lim_vec_lower     = cens_vec_1,
      cens_lim_vec_upper     = cens_vec_2,
      maxdev = maxdev,
      numclust = numclust,
      verbose = TRUE,
      niter = 10
  )
})
flowcut_profvis
saveRDS(flowcut_profvis, file = file.path("~/Downloads/flowcut-profvis.RDS"))
```

Comparing flowmix and flowcut times over many censoring limits.


```{r}
devtools::load_all("~/repos/flowmix-fork/flowmix")
censoring_limits = seq(from = 4, to = 1, length = 10)
number_of_censored_points =c()
flowcut_times = c()
for(icensor in 1:8){
  print(icensor)

  ## Generate data
  censoring_limit = censoring_limits[icensor]
  maxdev = .5
  
  ## Amount of censoring
  cens_vec_1 = c(-Inf,-Inf,rep(-Inf, dimdatt-2))
  cens_vec_2 = c(Inf,censoring_limit, rep(Inf, dimdatt-2))

  TT = 100
  nt = 300
 
  ## Generate data
  set.seed(100)
  datobj <-   gendat_flowcut(TT = TT, fac = .2 , nt = nt,
                             cens_lim_l_vec = cens_vec_1,
                             cens_lim_u_vec = cens_vec_2)
  datobj %>% list2env(envir = .GlobalEnv) %>% invisible()

  ## Save number of censored points
  convert_obj = my_convert(ylist, censor_indicator_left, 
                           censor_indicator_right)
  idx_cens_list = convert_obj$idx_cens_list
  number_of_censored_points[icensor] = sapply(idx_cens_list, length) %>% sum()

  
  begin_time = Sys.time()
  oneres <- flowcut_once(
      ylist = ylist,
      countslist = NULL,
      X = X,
      prob_lambda = 0.000001,
      mean_lambda = 0.000001,
      cens_indicator_list_left  = censor_indicator_left,
      cens_indicator_list_right = censor_indicator_right,
      cens_lim_vec_lower     = cens_vec_1,
      cens_lim_vec_upper     = cens_vec_2,
      maxdev = maxdev,
      numclust = numclust,
      verbose = TRUE
  )
  end_time = Sys.time()
  total_time = (end_time - begin_time) %>% as.numeric()


  flowcut_times[icensor] = total_time/(oneres$final.iter-1)
}


flowmix_time = sapply(1:5, function(ii){
  begin_time = Sys.time()
  
    ## Generate data
    set.seed(100)
    datobj <-   gendat_flowcut(TT = TT, fac = .2 , nt = nt,
                               cens_lim_l_vec = cens_vec_1,
                               cens_lim_u_vec = cens_vec_2)
    datobj %>% list2env(envir = .GlobalEnv) %>% invisible()
  
    oneres_flowmix <- flowmix_once(
        ylist = ylist,
        countslist = NULL,
        X = X,
        prob_lambda = 0.0001,
        mean_lambda = 0.0001,
        maxdev = maxdev,
        numclust = numclust,
        verbose = TRUE
    )
  end_time = Sys.time()
  total_time = (end_time - begin_time) %>% as.numeric()
  total_time/(oneres$final.iter-1)
}) %>% mean()

## Plot the results
par(mfrow=c(1,5))
plot(x = censoring_limits[1:8],
     y = flowcut_times,type='o', col = 'black', lwd = 2, ylim = c(0,max(flowcut_times)),
     main = "Per-iteration times", ylab = "Seconds", xlab = "censoring limit")
abline(h=flowmix_time, col = 'red', lwd = 2, lty = 2)
legend("topright", legend = c("flowcut", "flowmix"), lty = c(1,2), col = c(1,2), lwd = c(2,2))

plot(x = number_of_censored_points[1:8],
     y = flowcut_times,type='o', col = 'black', lwd = 2, ylim = c(0,max(flowcut_times)),
     main = "Per-iteration times", ylab = "Seconds", xlab = "Number of censored points")
abline(h=flowmix_time, col = 'red', lwd = 2, lty = 2)
legend("topleft", legend = c("flowcut", "flowmix"), lty = c(1,2), col = c(1,2), lwd = c(2,2))

plot(
    x = number_of_censored_points[1:8],
     y = flowcut_times,type='o', col = 'black', lwd = 2, ylim = c(0,max(flowcut_times)),
    main = "Per-iteration times", ylab = "Seconds", xlab = "Number of censored points", log = 'x')
abline(h=flowmix_time, col = 'red', lwd = 2, lty = 2)
legend("topleft", legend = c("flowcut", "flowmix"), lty = c(1,2), col = c(1,2), lwd = c(2,2))


plot(x = number_of_censored_points[1:8],
    y = (flowcut_times/flowmix_time), col = 'black', type = 'o', pch = 16, lwd = 2,
    ylab = "ratio", xlab = "Number of censored points",
    main = "Ratio of flowcut-to-flowmix")
legend("topleft", legend = c("flowcut/flowmix"), lty = c(1), col = c(1), pch = 16, lwd = c(2))
legend("bottomright", legend = paste((flowcut_times/flowmix_time) %>% round(2)), box.lwd=0)

plot(x = number_of_censored_points[1:8],
    y = (flowcut_times/flowmix_time), col = 'black', type = 'o', pch = 16, lwd = 2,
    ylab = "ratio", xlab = "Number of censored points\n(Out of 30,000)",
    main = "Ratio of flowcut-to-flowmix", log = "x")
legend("topleft", legend = c("flowcut/flowmix"), lty = c(1), col = c(1), pch = 16, lwd = c(2))
legend("bottomright", legend = paste((flowcut_times/flowmix_time) %>% round(2)), box.lwd=0)
```



# Measuring estimation errors.


```{r}
censoring_limits = seq(from=4,to=0, length = 12)
number_of_censored_points =c()
datobjs = flowcut_models = flowmix_models = list()
flowmix_uncens_models = list()
for(icensor in 1:12){
  print(icensor)

  ## Generate data
  censoring_limit = censoring_limits[icensor]
  maxdev = .5
  
  ## Amount of censoring
  cens_vec_1 = c(-Inf,-Inf,rep(-Inf, dimdatt-2))
  cens_vec_2 = c(Inf,censoring_limit, rep(Inf, dimdatt-2))

  TT = 100
  nt = 100
 
  ## Generate data
  set.seed(100)
  datobj <-   gendat_flowcut(TT = TT, fac = .2 , nt = nt,
                             cens_lim_l_vec = cens_vec_1,
                             cens_lim_u_vec = cens_vec_2)
  datobj %>% list2env(envir = .GlobalEnv) %>% invisible()

  ## Save number of censored points
  convert_obj = my_convert(ylist, censor_indicator_left, 
                           censor_indicator_right)
  idx_cens_list = convert_obj$idx_cens_list
  number_of_censored_points[icensor] = sapply(idx_cens_list, length) %>% sum()

  ## fitting flowcut
  oneres <- flowcut_once(
      ylist = ylist,
      countslist = NULL,
      X = X,
      prob_lambda = 0.000001,
      mean_lambda = 0.000001,
      cens_indicator_list_left  = censor_indicator_left,
      cens_indicator_list_right = censor_indicator_right,
      cens_lim_vec_lower     = cens_vec_1,
      cens_lim_vec_upper     = cens_vec_2,
      maxdev = maxdev,
      numclust = numclust,
      verbose = FALSE
  )

  ## fitting flowmix
  oneres_flowmix <- flowmix_once(
      ylist = ylist,
      countslist = NULL,
      X = X,
      prob_lambda = 0.0001,
      mean_lambda = 0.0001,
      maxdev = maxdev,
      numclust = numclust,
      verbose = FALSE)
  }

  ## fitting flowmix after removing the censored points
  convert_obj = my_convert(ylist, censor_indicator_left, censor_indicator_right)
  ylist_uncens = convert_obj$ylist_uncens

  oneres_flowmix_uncens <- flowmix_once(
      ylist = ylist_uncens,
      countslist = NULL,
      X = X,
      prob_lambda = 0.0001,
      mean_lambda = 0.0001,
      maxdev = maxdev,
      numclust = numclust,
      verbose = FALSE)

  flowcut_models[[icensor]] = oneres
  flowmix_models[[icensor]] = oneres_flowmix
  flowmix_uncens_models[[icensor]] = oneres_flowmix_uncens
  datobjs[[icensor]] = datobj
}


## Mean estimates, visualized
plotlist <-
lapply(1:12, function(icensor){
  datobj = datobjs[[icensor]]
  oneres = flowcut_models[[icensor]]
  oneres_flowmix = flowmix_models[[icensor]]
  oneres_uncens_flowmix = flowmix_uncens_models[[icensor]]
  datobj %>% list2env(envir = .GlobalEnv) %>% invisible()

flowmix_means = oneres_flowmix$mn %>% .[,idim,] %>% as_tibble() %>% setNames(1:2) %>%
  add_column(time = 1:TT) %>%
  pivot_longer(-time, names_to = "cluster", values_to = "mean")

flowmix_uncens_means = oneres_uncens_flowmix$mn %>% .[,idim,] %>% as_tibble() %>% setNames(1:2) %>%
  add_column(time = 1:TT) %>%
  pivot_longer(-time, names_to = "cluster", values_to = "mean")

true_means = datobj$mn %>% .[,idim,] %>% as_tibble() %>% setNames(1:2) %>%
    add_column(time = 1:TT) %>%
    pivot_longer(-time, names_to = "cluster", values_to = "mean")

plot_2d(oneres, ylist, idim = 2) +
    geom_line(aes(x=time, y = mean, group = cluster), data = flowmix_means,
              col = 'red', linewidth = 1.5)+
    geom_line(aes(x=time, y = mean, group = cluster), data = flowmix_uncens_means,
              col = 'violet', linewidth = 1.5, linetype = 'dotted')+
    geom_line(aes(x=time, y = mean, group = cluster), data = true_means,
              col = 'black', linewidth = 1.5)
})
cowplot::plot_grid(plotlist = plotlist, ncol = 4)


## Probability estimates, visualized
par(mfrow = c(3,4))
prop_of_censored_points = number_of_censored_points/10000
for(icensor in 1:12){
  matplot(datobj$pimat, col = 'black',
          type = 'l', lwd = 2,
          main = paste0("prop censored = ", round(prop_of_censored_points[icensor],2)), lty=1)
  matlines(flowmix_models[[icensor]]$prob, col = "red", type = 'l', lwd = 2, lty=1) 
  matlines(flowmix_uncens_models[[icensor]]$prob, col = "violet", type = 'l', lwd = 2, lty=1) 
  matlines(flowcut_models[[icensor]]$prob, col = "yellow", type = 'l', lwd = 2, lty=1) 
}


## Mean errors calculated
flowmix_mn_err = sapply(1:12, function(icensor){
  idim = 2 
  oneres = flowmix_models[[icensor]]
  my_ord = oneres$mn[,idim,] %>% apply(2, mean) %>% order()
  mn_est = oneres$mn[,idim,my_ord]
  mn_truth = datobj$mn[,idim,]
  err = mean((mn_est - mn_truth)^2)
})

flowcut_mn_err = sapply(1:12, function(icensor){
  idim = 2 
  oneres = flowcut_models[[icensor]]
  my_ord = oneres$mn[,idim,] %>% apply(2, mean) %>% order()
  mn_est = oneres$mn[,idim,my_ord]
  mn_truth = datobj$mn[,idim,]
  err = mean((mn_est - mn_truth)^2)
})


flowmix_uncens_mn_err = sapply(1:12, function(icensor){
  idim = 2 
  oneres = flowmix_uncens_models[[icensor]]
  my_ord = oneres$mn[,idim,] %>% apply(2, mean) %>% order()
  mn_est = oneres$mn[,idim,my_ord]
  mn_truth = datobj$mn[,idim,]
  err = mean((mn_est - mn_truth)^2)
})

my_palette <- c(
  "flowmix"     = "red",
  "flowmix_uncens" = "violet",
  "flowcut"  = "yellow"
)

data.frame(flowmix = flowmix_mn_err, flowcut = flowcut_mn_err, flowmix_uncens = flowmix_uncens_mn_err) %>%
  add_column(prop_censor = number_of_censored_points/10000) %>% 
  pivot_longer(-prop_censor) %>% 
  ggplot() +
  geom_line(aes(x=prop_censor, y = value, group = name, col = name), linewidth = rel(2))+
  scale_color_manual(values = my_palette) +
  xlab("Proportion of censored points") +
  ggtitle("L2 error in mean estimates (in 2nd dimension)")  +
  ylab("L2 error")  +
  theme_minimal()
```
